# Generated by Django 3.0.8 on 2020-07-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='makale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='Put your title here')),
                ('content', models.TextField(max_length=1000, null=True, verbose_name='Content here')),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
