# Generated by Django 3.0.8 on 2020-07-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='makale',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='makale',
            name='content',
            field=models.TextField(help_text='Makalenizin içeriğini yazınız.', max_length=1000, null=True, verbose_name='İçerik giriniz :'),
        ),
        migrations.AlterField(
            model_name='makale',
            name='title',
            field=models.CharField(help_text='Makalenizin başlığını yazınız.', max_length=50, null=True, verbose_name='Başlık giriniz :'),
        ),
    ]
