# Generated by Django 3.0.8 on 2020-07-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200717_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makale',
            name='slug',
            field=models.SlugField(editable=False, null=True, unique=True),
        ),
    ]
