# Generated by Django 3.0.8 on 2020-07-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200717_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='kategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=30, verbose_name='Kategori İsimi :')),
            ],
            options={
                'verbose_name_plural': 'Kategoriler',
            },
        ),
    ]
