# Generated by Django 3.0.8 on 2020-07-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_makale_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='makale',
            name='file',
            field=models.FileField(null=True, upload_to='', verbose_name='Medya Dosyası'),
        ),
    ]
