# Generated by Django 3.0.8 on 2020-07-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_makale_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makale',
            name='file',
            field=models.FileField(blank=True, default='default/default.jpg', help_text='Medya dosyanızı ekleyiniz.', null=True, upload_to='', verbose_name='Medya Dosyası'),
        ),
    ]
