# Generated by Django 3.0.8 on 2020-07-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200720_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makale',
            name='file',
            field=models.FileField(blank=True, default='default/default.jpg', help_text='Medya dosyanızı ekleyiniz.', null=True, upload_to='blog', verbose_name='Medya Dosyası'),
        ),
        migrations.AlterField(
            model_name='makale',
            name='kategori',
            field=models.ManyToManyField(blank=True, null=True, to='blog.kategori'),
        ),
    ]
