# Generated by Django 3.0.8 on 2020-07-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200720_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='makale',
            name='unique_id',
            field=models.CharField(editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='makale',
            name='file',
            field=models.FileField(blank=True, default='default/default.jpg', help_text='Medya dosyanızı ekleyiniz.', null=True, upload_to='', verbose_name='Medya Dosyası'),
        ),
    ]
