# Generated by Django 3.0.8 on 2020-07-20 14:31

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200720_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='makale',
            name='publish_secim',
            field=models.CharField(choices=[('yayin', 'YAYIN'), ('taslak', 'TASLAK')], default='yayin', max_length=6),
        ),
        migrations.AlterField(
            model_name='makale',
            name='file',
            field=models.FileField(blank=True, default='default/default.jpg', help_text='Medya dosyanızı ekleyiniz.', null=True, upload_to=blog.models.upload_to, verbose_name='Medya Dosyası'),
        ),
    ]
