# Generated by Django 3.0.8 on 2020-07-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200720_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='makale',
            name='publish_secim',
        ),
        migrations.AddField(
            model_name='makale',
            name='yayin_tipi',
            field=models.CharField(choices=[('yayin', 'Yayın'), ('taslak', 'Taslak')], default='yayin', max_length=6),
        ),
    ]
