# Generated by Django 3.0.8 on 2020-07-24 08:56

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200720_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makale',
            name='content',
            field=ckeditor.fields.RichTextField(help_text='Makalenizin içeriğini yazınız.', max_length=5000, null=True, verbose_name='İçerik giriniz :'),
        ),
        migrations.AlterField(
            model_name='makale',
            name='yayin_tipi',
            field=models.CharField(choices=[('hepsi', 'Hepsi'), ('yayin', 'Yayın'), ('taslak', 'Taslak')], default='yayin', max_length=6),
        ),
    ]
