# Generated by Django 3.0.8 on 2020-07-27 08:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20200727_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='yorum',
            field=ckeditor.fields.RichTextField(help_text='Yorumunuzu yazınız...', max_length=500, null=True, verbose_name='Yorum'),
        ),
    ]
